fastuph-web:
  build: docker/
  ports:
    - 9994:80
  volumes:
    - ./public_html:/var/www/html:ro
#    - ./configuration.php:/var/www/html/configuration.php:ro
  container_name: fastuphc_web
  links:
    - fastuph-db:db

fastuph-db:
  image: mariadb:10.0.38
  restart: always
  ports:
    - '33994:3306'
  volumes:
    - './docker/mysql:/var/lib/mysql'
  environment:
    - MYSQL_ROOT_PASSWORD=ITD@2019!
    - MYSQL_DATABASE=fastuph_dbv2
    - MYSQL_USER=fastuph_userv2
    - MYSQL_PASSWORD=]Uxl[LPF1,Bc
